os:
  - windows
  - linux
  - osx

language: c

env:
  - BRANCH=devel

cache:
  directories:
    - "$HOME/.choosenim"
    - "$TRAVIS_BUILD_DIR/git"

install:
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - nimble install -y -d
  - nimble test
