version = "5.0.0"
author = "disruptek"
description = "OpenAPI Code Generator"
license = "MIT"
requires "nim >= 2.0.0"
requires "npeg < 2.0.0"
requires "https://github.com/disruptek/rest.git >= 1.0.5 & < 2.0.0"
