name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        nim: [version-2-0, devel]
    name: '${{ matrix.os }} (${{ matrix.nim }})'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim }}

      - name: Install dependencies
        run: nimble --accept develop

      - name: Run tests
        run: |
          nim c -f -r tests/test.nim
          nim c -f -r tests/test3.nim
